export const Serviceslist = [
  {
    id: "1",
    name: "Consulting Services",
    info: "Expert advice to solve business challenges and make informed decisions",
    imageUrl: require("./assets/consulting.webp"),
    location: "123 Main Street, City, Country",
    openHours: "Monday-Friday: 9am-5pm",
    director: "John Smith",
    cost: "$100/hour",
  },
  {
    id: "2",
    name: "Web Design and Development",
    info: "Best in creating visually appealing and functional and responsive websites.",
    imageUrl: require("./assets/webdesign.avif"),
    location: "456 Elm Street, City, Country",
    openHours: "Monday-Friday: 9am-6pm",
    director: "Jane Doe",
    cost: "$1500/project",
  },
  {
    id: "3",
    name: "Digital Marketing",
    info: "Increasing brand visibility and driving website traffic through online strategies",
    imageUrl: require("./assets/digital.jpeg"),
    location: "789 Oak Street, City, Country",
    openHours: "Monday-Friday: 8am-5pm",
    director: "Michael Johnson",
    cost: "$2000/month",
  },
  {
    id: "4",
    name: "Software Development",
    info: "Building custom solutions to automate processes and improve efficiency",
    imageUrl: require("./assets/soft.jpeg"),
    location: "321 Pine Street, City, Country",
    openHours: "Monday-Friday: 9am-6pm",
    director: "Emily Williams",
    cost: "Starting from $5000",
  },
  {
    id: "5",
    name: "IT Support and Managed Services",
    info: "Technical support and maintenance for smooth operations",
    imageUrl: require("./assets/it.webp"),
    location: "654 Cedar Street, City, Country",
    openHours: "24/7",
    director: "David Brown",
    cost: "$100/hour",
  },
  {
    id: "6",
    name: "Graphic Design and Unique Branding",
    info: "Creating compelling brand identities and visual assets",
    imageUrl: require("./assets/grap.avif"),
    location: "987 Maple Street, City, Country",
    openHours: "Monday-Friday: 9am-5pm",
    director: "Sarah Wilson",
    cost: "$80/hour",
  },
  {
    id: "7",
    name: "Content Writing and Copywriting",
    info: "Producing engaging and informative written content for various purposes",
    imageUrl: require("./assets/content.jpeg"),
    location: "789 Oak Street, City, Country",
    openHours: "Monday-Friday: 8am-6pm",
    director: "Robert Thompson",
    cost: "$0.10/word",
  },
  {
    id: "8",
    name: "E-commerce Solutions",
    info: "Developing and managing online stores for selling products and services.",
    imageUrl: require("./assets/ecommerce.png"),
    location: "123 Main Street, City, Country",
    openHours: "Monday-Friday: 9am-5pm",
    director: "Jennifer Davis",
    cost: "Custom pricing",
  },
];
